version: '3'

vars:
  GOBIN: $(pwd)/bin

tasks:
     
  mock:
    cmds:
      # kafka
      - "{{.GOBIN}}/mockgen -package=mock -destination=kafka/mock/sync.go -source=kafka/sync.go"
      - "{{.GOBIN}}/mockgen -package=mock -destination=kafka/mock/async.go -source=kafka/async.go"
      - "{{.GOBIN}}/mockgen -package=mock -destination=kafka/mock/consumer_group.go -source=kafka/consumer_group.go"

  format:
    cmds:
      - task: go_files
        vars: { COMMAND: 'gofmt -w  {} +'}
      - task: go_files
        vars: { COMMAND: '{{.GOBIN}}/goimports -w  {} +'}

  test:
    cmds:
      - task: test-kafka
      - task: test-redis
      - task: test-cache
      - task: test-postgres

  test-kafka:
    cmds:
      - task: test-directory
        vars: { DIR: kafka }

  test-redis:
    cmds:
      - task: test-directory
        vars: { DIR: redis }

  test-postgres:
    cmds:
      - task: test-directory
        vars: { DIR: postgres }

  test-cache:
    cmds:
      - task: test-directory
        vars: { DIR: cache }

  lint:
    cmds:
      - "{{.GOBIN}}/revive
        -config revive.toml
        -formatter friendly
        -exclude ./**/mock
        ./..."

  commit:
    cmds:
      - task: format
      - task: lint
      - task: test

  deps:
    - GOBIN={{.GOBIN}} go install golang.org/x/tools/cmd/goimports@v0.19.0
    - GOBIN={{.GOBIN}} go install github.com/mgechev/revive@v1.3.7
    - GOBIN={{.GOBIN}} go install github.com/golang/mock/mockgen@v1.6.0
    - GOBIN={{.GOBIN}} go install github.com/mfridman/tparse@v0.17.0

  ## docker

  docker-up:
    cmds:
      - docker compose -f docker/docker-compose.yml up
  docker-down:
    cmds:
      - docker compose -f docker/docker-compose.yml down

  ## internal

  go_files:
    desc: "Return all .go files and run .COMMAND on them"
    internal: true
    cmds:
     - find .
        -name "*.go"
        -not -path ./mock
        -exec {{.COMMAND}};

  test-directory:
    dir: "{{.DIR}}"
    internal: true
    cmds:
      - go test -v -race -cover -json -coverprofile=coverage.out ./... > coverage.json && cd .. && {{.GOBIN}}/tparse -all -file={{.DIR}}/coverage.json
      - defer: rm coverage.json
